/-!
  License: Apache 2.0
  Copyright (c) Takeo Yamamoto

  Complete Physical AI
  --------------------

  Sensor
    ↓
  Perception
    ↓
  State Estimation
    ↓
  World Model
    ↓
  Prediction
    ↓
  Goal
    ↓
  Planning
    ↓
  Safety Shield
    ↓
  Controller
    ↓
  Actuator
    ↓
  Physical Plant
    ↓
  Observation
    ↺

  The planner is untrusted.
  The safety shield is trusted.
  Only a verified action or certified fallback can reach
  the physical plant.
-/

import WorldModel
import Mathlib.Tactic.Omega
import Mathlib.Tactic.Ring

namespace WorldModel

variable {S Z O A D G W : Type*}

/-!
============================================================
1. Physical Plant
============================================================
-/

/--
Physical plant.

S : physical state
A : action
O : observation
D : disturbance
-/
structure Plant (S A O D : Type*) where
  step  : S → A → D → S
  sense : S → O


/-!
============================================================
2. Perception
============================================================
-/

/--
Sensor/perception layer.

The physical world is converted into an observation.
-/
structure Perception (S O : Type*) where
  observe : S → O


/-!
============================================================
3. State Estimation
============================================================
-/

/--
Estimator converts observations into a latent physical state.

The estimator may be approximate.
Its correctness is supplied separately by the safety certificate.
-/
structure Estimator (O Z : Type*) where
  estimate : O → Z


/-!
============================================================
4. World Model
============================================================
-/

/--
Physical world model.

`encode` maps the physical belief into a computational world state.

`predict` predicts the result of applying an action.

`transition` is the computational world transition.
-/
structure PhysicalWorldModel (Z A W : Type*) where
  encode     : Z → W
  transition : W → A → W
  predict    : W → A → W


/-!
============================================================
5. Goal
============================================================
-/

/--
Goal evaluator.

A goal can represent:

* reaching a location
* maintaining velocity
* manipulation
* transportation
* tracking
* energy minimization
* task completion
-/
structure Goal (Z G : Type*) where
  generate : Z → G
  satisfied : Z → G → Prop


/-!
============================================================
6. Planner
============================================================
-/

/--
Untrusted planner.

The planner may be learned, optimized, heuristic,
model-predictive, or generated by another AI.
-/
structure Planner (Z G A : Type*) where
  plan : Z → G → A


/-!
============================================================
7. Controller
============================================================
-/

/--
Low-level controller.

The planner produces a high-level action.
The controller converts it into the physical actuator command.
-/
structure Controller (Z A : Type*) where
  control : Z → A → A


/-!
============================================================
8. Safety Shield
============================================================
-/

/--
Runtime safety shield.

Only actions accepted by this layer can reach the plant.
-/
structure SafetyShield (Z A : Type*) where
  check    : Z → A → Bool
  fallback : Z → A


/-!
============================================================
9. Complete Physical AI
============================================================
-/

/--
Complete Physical AI system.

This is the complete closed-loop architecture.
-/
structure PhysicalAI
    (S Z O A D G W : Type*) where

  plant : Plant S A O D

  perception : Perception S O

  estimator : Estimator O Z

  worldModel : PhysicalWorldModel Z A W

  goal : Goal Z G

  planner : Planner Z G A

  controller : Controller Z A

  shield : SafetyShield Z A


/-!
============================================================
10. Perception
============================================================
-/

/-- Raw observation. -/
def PhysicalAI.observe
    (P : PhysicalAI S Z O A D G W)
    (s : S) : O :=
  P.perception.observe s


/-- Estimated physical state. -/
def PhysicalAI.belief
    (P : PhysicalAI S Z O A D G W)
    (s : S) : Z :=
  P.estimator.estimate (P.observe s)


/-!
============================================================
11. World Model
============================================================
-/

/-- Computational representation of the current world. -/
def PhysicalAI.world
    (P : PhysicalAI S Z O A D G W)
    (s : S) : W :=
  P.worldModel.encode (P.belief s)


/-- Predict the world after an action. -/
def PhysicalAI.predict
    (P : PhysicalAI S Z O A D G W)
    (s : S)
    (a : A) : W :=
  P.worldModel.predict (P.world s) a


/-!
============================================================
12. Goal Generation
============================================================
-/

/-- Generate the current task from the estimated state. -/
def PhysicalAI.currentGoal
    (P : PhysicalAI S Z O A D G W)
    (s : S) : G :=
  P.goal.generate (P.belief s)


/-- Check whether the task has been completed. -/
def PhysicalAI.goalSatisfied
    (P : PhysicalAI S Z O A D G W)
    (s : S) : Prop :=
  P.goal.satisfied
    (P.belief s)
    (P.currentGoal s)


/-!
============================================================
13. Planning
============================================================
-/

/-- Untrusted high-level plan. -/
def PhysicalAI.proposal
    (P : PhysicalAI S Z O A D G W)
    (s : S) : A :=
  P.planner.plan
    (P.belief s)
    (P.currentGoal s)


/-- Low-level control command. -/
def PhysicalAI.controlCommand
    (P : PhysicalAI S Z O A D G W)
    (s : S) : A :=
  P.controller.control
    (P.belief s)
    (P.proposal s)


/-!
============================================================
14. Safety Shield
============================================================
-/

/--
Fail-closed action selection.

No unchecked action can reach the physical plant.
-/
def PhysicalAI.safeAction
    (P : PhysicalAI S Z O A D G W)
    (s : S) : A :=
  let z := P.belief s
  let a := P.controlCommand s

  if P.shield.check z a = true then
    a
  else
    P.shield.fallback z


/-- Accepted action theorem. -/
theorem PhysicalAI.safeAction_of_check
    (P : PhysicalAI S Z O A D G W)
    (s : S)
    (h :
      P.shield.check
        (P.belief s)
        (P.controlCommand s) = true) :
    P.safeAction s =
      P.controlCommand s := by

  simp [PhysicalAI.safeAction, h]


/-- Rejected action theorem. -/
theorem PhysicalAI.safeAction_of_reject
    (P : PhysicalAI S Z O A D G W)
    (s : S)
    (h :
      P.shield.check
        (P.belief s)
        (P.controlCommand s) ≠ true) :
    P.safeAction s =
      P.shield.fallback (P.belief s) := by

  simp [PhysicalAI.safeAction, h]


/--
Every action entering the physical plant is either:

1. a verified controller command, or
2. the fallback.
-/
theorem PhysicalAI.safeAction_certified
    (P : PhysicalAI S Z O A D G W)
    (s : S) :
    P.shield.check
        (P.belief s)
        (P.safeAction s) = true
      ∨
    P.safeAction s =
      P.shield.fallback (P.belief s) := by

  by_cases h :
      P.shield.check
        (P.belief s)
        (P.controlCommand s) = true

  · left
    rw [P.safeAction_of_check s h]
    exact h

  · right
    exact P.safeAction_of_reject s h


/-!
============================================================
15. Physical Actuation
============================================================
-/

/--
Actual physical transition.

This is not a simulation result.
It is the transition defined by the physical plant interface.
-/
def PhysicalAI.act
    (P : PhysicalAI S Z O A D G W)
    (s : S)
    (d : D) : S :=
  P.plant.step
    s
    (P.safeAction s)
    d


/-!
============================================================
16. Complete Physical Cycle
============================================================
-/

/--
One complete physical-AI cycle.

sense
→ estimate
→ world model
→ goal
→ plan
→ control
→ safety shield
→ act
→ physical state
-/
def PhysicalAI.cycle
    (P : PhysicalAI S Z O A D G W)
    (s : S)
    (d : D) : S :=
  P.act s d


/-!
============================================================
17. Closed-Loop Execution
============================================================
-/

/--
Run the physical AI against a disturbance sequence.
-/
def PhysicalAI.run
    (P : PhysicalAI S Z O A D G W) :
    S → List D → S
  | s, [] => s
  | s, d :: ds =>
      P.run (P.cycle s d) ds


/-!
============================================================
18. Safety Certificate
============================================================
-/

/--
Formal safety contract.

The safety proof covers:

* state estimation consistency
* accepted actions
* fallback actions
* disturbances
* physical transitions
-/
structure SafetyCase
    (P : PhysicalAI S Z O A D G W) where

  Safe : S → Prop

  Consistent : Z → S → Prop

  DistOk : D → Prop

  sense_sound :
    ∀ s,
      Consistent
        (P.belief s)
        s

  action_safe :
    ∀ z s a,
      Consistent z s →
      Safe s →
      P.shield.check z a = true →
      ∀ d,
        DistOk d →
        Safe
          (P.plant.step s a d)

  fallback_safe :
    ∀ z s,
      Consistent z s →
      Safe s →
      ∀ d,
        DistOk d →
        Safe
          (P.plant.step
            s
            (P.shield.fallback z)
            d)


/-!
============================================================
19. One-Step Safety
============================================================
-/

/--
The complete physical AI preserves the certified safe set.
-/
theorem PhysicalAI.step_safe
    (P : PhysicalAI S Z O A D G W)
    (C : SafetyCase P)
    {s : S}
    (hs : C.Safe s)
    {d : D}
    (hd : C.DistOk d) :
    C.Safe (P.cycle s d) := by

  unfold PhysicalAI.cycle
  unfold PhysicalAI.act

  by_cases h :
      P.shield.check
        (P.belief s)
        (P.controlCommand s) = true

  · rw [P.safeAction_of_check s h]

    exact
      C.action_safe
        (P.belief s)
        s
        (P.controlCommand s)
        (C.sense_sound s)
        hs
        h
        d
        hd

  · rw [P.safeAction_of_reject s h]

    exact
      C.fallback_safe
        (P.belief s)
        s
        (C.sense_sound s)
        hs
        d
        hd


/-
============================================================
20. Arbitrary-Length Safety
============================================================
-/

/--
Safety remains invariant for the complete physical run.
-/
theorem PhysicalAI.run_safe
    (P : PhysicalAI S Z O A D G W)
    (C : SafetyCase P) :
    ∀ ds : List D,
      (∀ d ∈ ds, C.DistOk d) →
      ∀ s,
        C.Safe s →
        C.Safe (P.run s ds) := by

  intro ds

  induction ds with

  | nil =>
      intro _ s hs
      exact hs

  | cons d ds ih =>
      intro hds s hs

      have hd : C.DistOk d :=
        hds d (by simp)

      have hds' :
          ∀ e ∈ ds, C.DistOk e :=
        fun e he =>
          hds e (by simp [he])

      exact
        ih
          hds'
          _
          (P.step_safe C hs hd)


/-!
============================================================
21. Certified Physical AI
============================================================
-/

/-- A Physical AI is certified when a SafetyCase exists. -/
def Certified
    (P : PhysicalAI S Z O A D G W) : Prop :=
  Nonempty (SafetyCase P)


/--
Certified physical AI preserves safety under
every certified disturbance sequence.
-/
theorem certified_run_safe
    (P : PhysicalAI S Z O A D G W)
    (C : SafetyCase P)
    (ds : List D)
    (hds : ∀ d ∈ ds, C.DistOk d)
    (s : S)
    (hs : C.Safe s) :
    C.Safe (P.run s ds) :=
  P.run_safe C ds hds s hs


end WorldModel
